### ISSUE TITLE
[Feature]: Librarian "What games can be played with X people?" feature

### ISSUE THREAD

**Issue by stanbery** [ZinkNotTheMetal/tennessee-game-days#148]
### New feature you are looking for

For the librarian, a place (tab?) where they can query the library for what games can be played with X people. Query would check min-max player count, return the list of games that can support the count. Additionally, this could be expanded to search by game mechanic.  Further, it could potentially be set to select a random game, in the library, and not checked out, with those qualifications (player count, mechanic(s)).

**Comment by ZinkNotTheMetal** [comment]
I would really like to create a react native app that people 'could' install on their phone that would give access to the library database. It would also help user management because then they could just do it if they change their name and we could tie that download to an account and give us the functionality that we want eventually anyways.

I could create messaging to publish new things, get a calendar together where people could save their schedule and get reminders. This is where I would love to head, but I know this would be a big effort. Was going to get this implemented and see if anyone else wanted to help on that side of the house. My thought is a react native project

**Comment by ZinkNotTheMetal** [comment]
I think #169 is probably the best fix for now until we get the app going
